/*
 * File: app/view/formLogin.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.formLogin', {
    extend: 'Ext.form.Panel',

    config: {
        title: 'Login',
        itemId: 'formLogin',
        ui: 'light',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'fieldset',
                itemId: 'fieldLogin',
                ui: 'dark',
                title: 'Login',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'txtUsername',
                        label: 'UserName',
                        name: 'username',
                        placeHolder: 'enter name'
                    },
                    {
                        xtype: 'passwordfield',
                        itemId: 'txtPassword',
                        label: 'Password',
                        name: 'password',
                        placeHolder: 'enter password'
                    },
                    {
                        xtype: 'container',
                        itemId: 'mycontainer',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'cmdLogin',
                                margin: 10,
                                ui: 'round',
                                iconCls: 'action',
                                text: 'login'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});