/*
 * File: app/view/frmSignOff.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.frmSignOff', {
    extend: 'Ext.Container',

    config: {
        title: 'Job Sign Off',
        itemId: 'frmSignOff',
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'cmdSignOffSave',
                        ui: 'round',
                        text: 'save'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'fldEmployee',
                title: 'Worker In Charge',
                items: [
                    {
                        xtype: 'signaturefield',
                        itemId: 'txtEmployeeSignature'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'fldCustomer',
                title: 'Customer',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'txtCustomerName',
                        label: 'Name',
                        name: 'name'
                    },
                    {
                        xtype: 'signaturefield',
                        sigPlaceHolder: 'tap to sign',
                        itemId: 'txtCustomerSignature'
                    }
                ]
            }
        ]
    }

});