/*
 * File: app/view/inventoryPicker.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.inventoryPicker', {
    extend: 'Ext.Container',

    config: {
        itemId: 'inventoryPicker',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                id: 'inventoryToolbar',
                itemId: 'inventoryToolbar',
                title: '',
                items: [
                    {
                        xtype: 'button',
                        id: 'inventoryToolbarCancel',
                        ui: 'round',
                        text: 'cancel'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'inventoryToolbarDone',
                        ui: 'round',
                        text: 'done'
                    }
                ]
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Inventory List'
            },
            {
                xtype: 'list',
                id: 'inventoryListMain',
                itemId: 'inventoryListMain',
                autoDestroy: false,
                mode: 'MULTI',
                emptyText: 'no items available',
                itemTpl: [
                    '<div>{itemNumber} - {name}</div>'
                ],
                store: 'InventoryMain'
            }
        ]
    }

});