/*
 * File: app/view/ListContainer.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.ListContainer', {
    extend: 'Ext.Container',
    alias: 'widget.Listcontainer',

    config: {
        id: 'ListContainer',
        itemId: 'ListContainer',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                id: 'listAppointment',
                itemId: 'listAppointment',
                itemCls: 'action',
                itemTpl: [
                    '<div>{subject} ({duration})<span style="float:right;">Start: {start}</span></div>'
                ],
                store: 'Appointments',
                triggerCtEvent: 'itemtap',
                iconCls: 'action'
            }
        ]
    }

});