/*
 * File: app/view/navMain.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.navMain', {
    extend: 'Ext.navigation.View',

    config: {
        title: '',
        itemId: 'navMain',
        autoDestroy: false,
        layout: {
            animation: 'slide',
            type: 'card'
        },
        navigationBar: {
            itemId: 'navMainBar'
        },
        items: [
            {
                xtype: 'container',
                title: 'Lightning',
                itemId: 'conSwitchBoard',
                layout: {
                    align: 'center',
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'cmdTimesheets',
                        ui: 'round',
                        text: 'Timesheets'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'cmdAppointments',
                        ui: 'round',
                        text: 'Appointments'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'Logoff',
                        ui: 'round',
                        text: 'Logoff'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            }
        ]
    }

});