/*
 * File: app/view/panRiskList.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.panRiskList', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                scrollable: false,
                title: 'List'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'cmdCancel',
                        ui: 'action-round',
                        text: 'cancel'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'cmdSave',
                        ui: 'action-round',
                        text: 'save'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'lstMeasures1',
                itemTpl: [
                    '<div><input type=\'checkbox\' id=\'chkSelected\' {checked}/> {Description}</div>'
                ],
                store: 'strRiskList'
            }
        ]
    }

});