/*
 * File: app/view/RiskTask.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.RiskTask', {
    extend: 'Ext.form.Panel',

    requires: [
        'Mob2.view.txtReadOnly'
    ],

    config: {
        title: 'Tasks',
        itemId: 'RiskTask',
        style: '.x-list-normal .x-list-item.x-list-item-tpl, .x-list-normal .x-list-item .x-dock-horizontal {     border-top: 1px solid #dedede;     background: #ffffff; }',
        scrollable: true,
        items: [
            {
                xtype: 'textfield',
                itemId: 'txtName',
                label: 'Name',
                name: 'name',
                placeHolder: 'enter task name'
            },
            {
                xtype: 'spacer',
                height: '20px',
                style: 'background-color:white;'
            },
            {
                xtype: 'fieldset',
                itemId: 'fldHazards',
                layout: {
                    type: 'fit'
                },
                title: 'Hazards',
                items: [
                    {
                        xtype: 'list',
                        scrollable: false,
                        itemId: 'lstHazard',
                        emptyText: 'no hazards available',
                        itemCls: 'clear',
                        itemTpl: [
                            '<div>{Description}<span style=\'float:right;visibility:{Checked};\'><img src=\'images/tick.gif\' /><span><input type=\'hidden\' id=hidChecked{xindex} value=\'{Checked}\'/></div>',
                            '    '
                        ],
                        scrollToTopOnRefresh: false,
                        selectedCls: 'css',
                        store: 'RiskMain'
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: '20px',
                style: 'background-color:white;'
            },
            {
                xtype: 'fieldset',
                itemId: 'fldRisks',
                layout: {
                    type: 'fit'
                },
                title: 'Risks',
                items: [
                    {
                        xtype: 'list',
                        scrollable: false,
                        itemId: 'lstRisks',
                        emptyText: 'no risk items available',
                        itemTpl: [
                            '<div>{Description}<span style=\'float:right;visibility:{Checked};\'><img src=\'images/tick.gif\' /><span><input type=\'hidden\' id=hidChecked{xindex} value=\'{Checked}\'/></div>'
                        ],
                        selectedCls: 'css',
                        store: 'RiskMain'
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: '20px',
                style: 'background-color:white;'
            },
            {
                xtype: 'txtreadonly',
                itemId: 'txtRiskRating',
                label: 'Risk Rating',
                name: 'riskRating',
                placeHolder: 'tap to set'
            },
            {
                xtype: 'spacer',
                height: '20px',
                style: 'background-color:white;'
            },
            {
                xtype: 'fieldset',
                itemId: 'fldMeasures',
                layout: {
                    type: 'fit'
                },
                title: 'Measures',
                items: [
                    {
                        xtype: 'list',
                        scrollable: false,
                        itemId: 'lstMeasures',
                        emptyText: 'no measures available',
                        itemTpl: [
                            '<div>{Description}<span style=\'float:right;visibility:{Checked};\'><img src=\'images/tick.gif\' /><span><input type=\'hidden\' id=hidChecked{xindex} value=\'{Checked}\'/></div>'
                        ],
                        selectedCls: 'css',
                        store: 'RiskMain'
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: '20px',
                style: 'background-color:white;'
            },
            {
                xtype: 'selectfield',
                itemId: 'ddlHierarchy',
                label: 'Hierarchy',
                name: 'hierarchy',
                placeHolder: 'select',
                autoSelect: false,
                store: 'RiskHierarchy',
                valueField: 'recordID'
            },
            {
                xtype: 'textareafield',
                itemId: 'txtResidual',
                label: 'Residual',
                name: 'residualRating',
                readOnly: true
            },
            {
                xtype: 'spacer',
                height: '20px',
                style: 'background-color:white;'
            },
            {
                xtype: 'component',
                height: '30px',
                html: '<span style=\'valign:middle;\'>Comments</span>',
                itemId: 'lblComments'
            },
            {
                xtype: 'textfield',
                height: '150px',
                itemId: 'txtComments',
                name: 'comments',
                placeHolder: 'enter comments'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'hidID',
                name: 'id'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'hidAppointmentID',
                name: 'appointmentID'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'hidMode',
                name: 'mode'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'hidRRColour',
                name: 'mode'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'cmdTaskCancel',
                        ui: 'round',
                        text: 'cancel'
                    },
                    {
                        xtype: 'button',
                        itemId: 'cmdTaskSave',
                        ui: 'round',
                        text: 'save'
                    },
                    {
                        xtype: 'button',
                        itemId: 'cmdTaskDelete',
                        ui: 'round',
                        text: 'delete'
                    }
                ]
            }
        ]
    }

});