/*
 * File: app/view/RiskList.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.RiskList', {
    extend: 'Ext.Container',

    config: {
        title: 'Task List',
        itemId: 'RiskList',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                itemId: 'mytoolbar3',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'cmdTaskBack',
                        ui: 'round',
                        text: 'back'
                    },
                    {
                        xtype: 'button',
                        itemId: 'cmdTaskAdd',
                        ui: 'round',
                        text: 'add'
                    },
                    {
                        xtype: 'button',
                        itemId: 'cmdListNext',
                        ui: 'round',
                        text: 'next'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'lstTasks',
                emptyText: 'no tasks available',
                itemTpl: [
                    '<div>{name}</div>'
                ],
                store: 'RiskMain'
            }
        ]
    }

});