/*
 * File: app/view/RiskRating.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.RiskRating', {
    extend: 'Ext.Container',

    config: {
        title: 'Risk Rating',
        itemId: 'RiskRating',
        layout: {
            type: 'vbox'
        },
        scrollable: true,
        items: [
            {
                xtype: 'container',
                itemId: 'ImageContainer',
                items: [
                    {
                        xtype: 'component',
                        html: '<img src=\'resources/images/RiskMatrix1.png\' alt=\'Risk Matrix\'/>',
                        itemId: 'imgRisk'
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'mycontainer2',
                style: 'margin-top:20px;margin-bottom:20px',
                layout: {
                    type: 'vbox'
                }
            },
            {
                xtype: 'selectfield',
                itemId: 'ddlLikelihood',
                label: 'Likelihood',
                placeHolder: 'select Likelihood',
                autoSelect: false,
                store: 'RiskLikeliHood'
            },
            {
                xtype: 'selectfield',
                itemId: 'ddlConsequences',
                label: 'Consequences',
                placeHolder: 'select Consequences',
                autoSelect: false,
                store: 'RiskConsequences'
            },
            {
                xtype: 'textfield',
                itemId: 'txtRisk',
                width: '50%',
                label: 'Risk',
                labelWidth: '80%',
                readOnly: true
            },
            {
                xtype: 'textareafield',
                itemId: 'txtResidual',
                label: 'Residual',
                readOnly: true
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                itemId: '',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'cmdRatingSave',
                        ui: 'round',
                        text: 'save'
                    }
                ]
            },
            {
                xtype: 'hiddenfield',
                itemId: 'hidConsequences'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'hidLikelihood'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'hidColour'
            }
        ]
    },

    ddlSelectChange: function(type, newValue) {
        var me = this;
        var hidConsequences = me.down('#hidConsequences').getValue();
        var  hidLikelihood = me.down('#hidLikelihood').getValue();
        if (hidConsequences !=='' ||hidLikelihood !== ''){


        }
    }

});