/*
 * File: app/view/timePicker.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.timePicker', {
    extend: 'Ext.picker.Picker',

    config: {
        itemId: 'timePicker',
        useTitles: true,
        doneButton: {
            itemId: 'tpCmdDone',
            ui: 'action-round'
        },
        cancelButton: {
            itemId: 'tpCmdCancel',
            ui: 'round'
        },
        slots: [
            {
                xtype: 'pickerslot',
                data: [
                    {
                        text: '01',
                        value: 1
                    }
                ],
                id: 'hours',
                itemId: 'hours',
                autoDestroy: false,
                name: 'hours',
                title: 'Hours'
            },
            {
                xtype: 'pickerslot',
                data: [
                    {
                        text: '01',
                        value: 1
                    }
                ],
                id: 'minutes',
                itemId: 'minutes',
                name: 'minutes',
                title: 'Minutes'
            },
            {
                xtype: 'pickerslot',
                data: [
                    {
                        text: 'am',
                        value: 0
                    },
                    {
                        text: 'pm',
                        value: 1
                    }
                ],
                id: 'ampm',
                itemId: 'ampm',
                name: 'ampm',
                title: ''
            }
        ],
        toolbar: {
            xtype: 'titlebar',
            docked: 'top',
            id: 'pickerBar'
        }
    }

});