/*
 * File: app/view/tsDayDetails.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.tsDayDetails', {
    extend: 'Ext.form.Panel',

    requires: [
        'Mob2.view.txtReadOnly'
    ],

    config: {
        itemId: 'tsDayDetails',
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'cmdTimeSave',
                        ui: 'round',
                        text: 'save'
                    }
                ]
            },
            {
                xtype: 'component',
                height: '40px',
                itemId: 'lblDate'
            },
            {
                xtype: 'selectfield',
                itemId: 'ddlLeave',
                label: 'Leave',
                name: 'typeID',
                displayField: 'description',
                store: 'TSType',
                usePicker: true,
                valueField: 'typeID'
            },
            {
                xtype: 'txtreadonly',
                itemId: 'txtTimeStart',
                label: 'Time start',
                placeHolder: 'tap to set'
            },
            {
                xtype: 'txtreadonly',
                itemId: 'txtTimeEnd',
                label: 'Time End',
                placeHolder: 'tap to set'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'hidLastTime'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'hidRow'
            }
        ]
    }

});