/*
 * File: app/view/txtReadOnly.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mob2.view.txtReadOnly', {
    extend: 'Ext.field.Text',
    alias: 'widget.txtreadonly',

    config: {
        itemId: 'txtReadOnly2',
        label: 'Field',
        readOnly: true
    },

    initialize: function() {
        var me = this;
        me.element.on('tap', 'doTap', me);
        me.callParent();


    },

    doTap: function(e, t) {
        this.fireEvent('tap', this, e, t);
    }

});